# Generated by Django 4.2.3 on 2023-07-15 17:55

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do ": "The issue is not started",
        "in progress": "Issue is in progress",
        "done": "The issue is completed",
    }
    Status = apps.get_model('issues', 'Status')
    for name, description in entries.items():
        status_obj = Status(name=name, description=description)
        status_obj.save()

def populate_priority(apps, schemaeditor):
    entries = {
        "low": "The issue is easy to solve",
        "medium": "The issue is not easy to solve",
        "high": "The issue is hard to solve",
    }
    Priority = apps.get_model('issues', 'Priority')
    for name, description in entries.items():
        status_obj = Priority(name=name, description=description)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_priority),
        migrations.RunPython(populate_status),
    ]
